package com.luannh.lsa.model;
// Generated Nov 7, 2017 5:37:57 PM by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Employees generated by hbm2java
 */
@Entity
@Table(name = "employees")
public class Employees implements java.io.Serializable {

	private int empId;
	private Merits merits;
	private String empName;
	private Float salary;

	public Employees() {
	}

	public Employees(int empId, String empName) {
		this.empId = empId;
		this.empName = empName;
	}

	public Employees(int empId, Merits merits, String empName, Float salary) {
		this.empId = empId;
		this.merits = merits;
		this.empName = empName;
		this.salary = salary;
	}

	@Id

	@Column(name = "emp_id", unique = true, nullable = false)
	public int getEmpId() {
		return this.empId;
	}

	public void setEmpId(int empId) {
		this.empId = empId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "performance")
	public Merits getMerits() {
		return this.merits;
	}

	public void setMerits(Merits merits) {
		this.merits = merits;
	}

	@Column(name = "emp_name", nullable = false)
	public String getEmpName() {
		return this.empName;
	}

	public void setEmpName(String empName) {
		this.empName = empName;
	}

	@Column(name = "salary", precision = 12, scale = 0)
	public Float getSalary() {
		return this.salary;
	}

	public void setSalary(Float salary) {
		this.salary = salary;
	}

}
