package com.luannh.lsa.model;
// Generated Nov 7, 2017 5:37:57 PM by Hibernate Tools 5.0.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Merits generated by hbm2java
 */
@Entity
@Table(name = "merits")
public class Merits implements java.io.Serializable {

	private int performance;
	private float percentage;
	private Set<Employees> employeeses = new HashSet<Employees>(0);

	public Merits() {
	}

	public Merits(int performance, float percentage) {
		this.performance = performance;
		this.percentage = percentage;
	}

	public Merits(int performance, float percentage, Set<Employees> employeeses) {
		this.performance = performance;
		this.percentage = percentage;
		this.employeeses = employeeses;
	}

	@Id

	@Column(name = "performance", unique = true, nullable = false)
	public int getPerformance() {
		return this.performance;
	}

	public void setPerformance(int performance) {
		this.performance = performance;
	}

	@Column(name = "percentage", nullable = false, precision = 12, scale = 0)
	public float getPercentage() {
		return this.percentage;
	}

	public void setPercentage(float percentage) {
		this.percentage = percentage;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "merits")
	public Set<Employees> getEmployeeses() {
		return this.employeeses;
	}

	public void setEmployeeses(Set<Employees> employeeses) {
		this.employeeses = employeeses;
	}

}
